server:
  port : 8081

Spring:
  redis:
    database: 0
    host: 101.34.214.118
    post: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 6000